<?php
if ( function_exists( 'acf_register_block_type' ) ) :
    function dutchtown_acf_init_quick_contact()
    {
        acf_register_block_type( array(
            'name'              => 'dutchtown_quick_contact',
            'title'             => __('Dutchtown Quick Contact'),
            'description'       => __('At a glance contact info.'),
            'render_template'   => dutchtown_acf_blocks_dir() . 'block-templates/block-quick-contact.php',
            'category'          => 'formatting',
            'icon'              => dutchtown_icon(),
            'enqueue_style'     => plugin_dir_url( __DIR__ ) . 'css/quick-contact/quick-contact.css',
            'keywords'          => array( 'contact', 'dutchtown' ),
            'supports'          => array ( 'align' => false ),
            'mode'              => 'edit'
        ));
    }
    add_action( 'acf/init', 'dutchtown_acf_init_quick_contact' );
endif;

if ( function_exists( 'acf_add_local_field_group' ) ) :
    acf_add_local_field_group(array(
        'key' => 'group_5ff87cafc1093',
        'title' => 'Quick Contact Fields',
        'fields' => array(
            array(
                'key' => 'field_5ff87cba6f88e',
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ff87d196f893',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ff87cce6f88f',
                'label' => 'Phone',
                'name' => 'phone',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ff87ce66f890',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5ff87cf56f891',
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5ff87cfe6f892',
                'label' => 'Website',
                'name' => 'website',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6702f14290e5d',
                'label' => 'Style',
                'name' => 'style',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'black-yellow' => 'Yellow on Black',
                    'yellow-black' => 'Black on Yellow',
                ),
                'default_value' => 'black-yellow',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6702f14290e6d',
                'label' => 'Align Box',
                'name' => 'align_box',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'align-left' => 'Left',
                    'align-right' => 'Right'
                ),
                'default_value' => 'right',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6702f14290e7d',
                'label' => 'Align Text',
                'name' => 'align_text',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'align-text-left' => 'Left',
                    'align-text-center' => 'Center',
                    'align-text-right' => 'Right'
                ),
                'default_value' => 'left',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/dutchtown-quick-contact',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
endif;